#!bash
#
# bash completion support for n98-magerun.phar console
#
# Thanks to atthieu Bontemps <matthieu@knplabs.com> for
# the original script.
#
# https://github.com/knplabs/symfony2-autocomplete/blob/master/symfony2-autocomplete.bash

_console()
{
    local cur prev opts cmd
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    cmd="${COMP_WORDS[0]}"
    PHP='$ret = shell_exec($argv[1]);

$ret = preg_replace("/^.*Available commands:\n/s", "", $ret);
$ret = explode("\n", $ret);

$comps = array();
foreach ($ret as $line) {
    if (preg_match("@^  ([^ ]+) @", $line, $m)) {
        $comps[] = $m[1];
    }
}

echo implode("\n", $comps);
'
    possible=$($(which php) -r "$PHP" $COMP_WORDS);
    COMPREPLY=( $(compgen -W "${possible}" -- ${cur}) )
    return 0
}

complete -F _console n98-magerun.phar
COMP_WORDBREAKS=${COMP_WORDBREAKS//:}