<?php echo $this->xmlProlog() ?>
<config>
    <modules>
        <<?php echo $vendorNamespace ?>_<?php echo $moduleName ?>>
            <version>1.0.0</version>
        </<?php echo $vendorNamespace ?>_<?php echo $moduleName ?>>
    </modules>
    <global>
<?php if ($createBlocks): ?>
        <blocks>
            <class><?php echo $vendorNamespace ?>_<?php echo $moduleName ?>_Block</class>
        </blocks>
<?php endif; ?>
<?php if ($createHelpers): ?>
        <helpers>
            <class><?php echo $vendorNamespace ?>_<?php echo $moduleName ?>_Helper</class>
        </helpers>
<?php endif; ?>
<?php if ($createModels): ?>
        <models>
            <class><?php echo $vendorNamespace ?>_<?php echo $moduleName ?>_Model</class>
        </models>
<?php endif; ?>
    </global>
</config>