<?php

$gitHubUrl = 'https://github.com/' . strtolower($vendorNamespace) . '/' . $vendorNamespace . '_' . $moduleName;

?><?php echo $vendorNamespace ?> <?php echo $moduleName ?> Extension
=====================
This is a short description of what the extension does.

Facts
-----
- version: 0.1.0
- extension key: <?php echo $vendorNamespace ?>_<?php echo $moduleName ?><?php echo PHP_EOL ?>
- [extension on Magento Connect](http://www.magentocommerce.com/magento-connect/<?php echo strtolower($vendorNamespace) ?>-<?php echo strtolower($moduleName) ?>-1234.html)
- Magento Connect 1.0 extension key: magento-community/<?php echo $vendorNamespace ?>_<?php echo $moduleName ?><?php echo PHP_EOL ?>
- Magento Connect 2.0 extension key: http://connect20.magentocommerce.com/community/<?php echo $vendorNamespace ?>_<?php echo $moduleName ?><?php echo PHP_EOL ?>
- [extension on GitHub](<?php echo $gitHubUrl ?>)
- [direct download link](http://connect.magentocommerce.com/community/get/<?php echo $vendorNamespace ?>_<?php echo $moduleName ?>-0.1.0.tgz)

Description
-----------
This paragraph describes what the extension does.

Requirements
------------
- PHP >= 5.2.0
- Mage_Core
- ...

Compatibility
-------------
- Magento >= 1.4

Installation Instructions
-------------------------
1. Install the extension via Magento Connect with the key shown above or copy all the files into your document root.
2. Clear the cache, logout from the admin panel and then login again.
3. Configure and activate the extension under System - Configuration - Company - Example Extension.
4. ...

Uninstallation
--------------
1. Remove all extension files from your Magento installation
2. ...

Support
-------
If you have any issues with this extension, open an issue on [GitHub](<?php echo $gitHubUrl ?>/issues).

Contribution
------------
Any contribution is highly appreciated. The best way to contribute code is to open a [pull request on GitHub](https://help.github.com/articles/using-pull-requests).

Developer
---------
FirstName LastName
[http://www.firstname-lastname.com](http://www.firstname-lastname.com)
[@FirstNameLastName](https://twitter.com/FirstNameLastName)

Licence
-------
[OSL - Open Software Licence 3.0](http://opensource.org/licenses/osl-3.0.php)

Copyright
---------
(c) 2012 <?php echo $vendorNamespace ?>
