{
    "name": "<?php echo $vendorNamespace ?>/<?php echo $moduleName ?>",
    "license": "OSL-3.0",
    "type": "magento-module",
    "description": "<?php echo $description ? $description : 'Add your description here' ?>",
    "require": {
        "magento-hackathon/magento-composer-installer": "dev-master"
    },
    "authors":[
        {
            "name":"<?php echo $authorName ? $authorName : 'Add your name here' ?>",
            "email":"<?php echo $authorEmail ? $authorEmail : 'Add your email address here' ?>"
        }
    ]
}