name: Test Magento Open Source 1.9 with PHP 7.4

on: [push, pull_request]

jobs:
  test-magento-open-source-1-9:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: magento_test_db
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v3

      - name: Linux Setup
        run: ./.github/workflows/linux-setup.sh

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: yaml
          coverage: none

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/composer
            vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Validate mysql service
        run: |
          echo "Checking mysql service"
          sudo apt-get install -y mysql-client
          mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports['3306'] }} -uroot -proot -e "SHOW DATABASES"

      - name: Install Magento
        run: |
          php bin/n98-magerun install \
          --magentoVersionByName="openmage-19.4.23" \
          --installationFolder="./magento" \
          --dbHost="127.0.0.1" \
          --dbPort="${{ job.services.mysql.ports['3306'] }}" \
          --dbUser="root" \
          --dbPass="root" \
          --dbName="magento_test_db" \
          --installSampleData=no \
          --useDefaultConfigParams=yes \
          --baseUrl="http://magento.local/"

      - name: Set Magento root environment variable
        run: echo "N98_MAGERUN_TEST_MAGENTO_ROOT=${{ github.workspace }}/magento" >> $GITHUB_ENV

      - name: Run tests
        run: php -f vendor/bin/phpunit

      - name: Report coverage
        uses: codecov/codecov-action@v3
        with:
          file: ./build/coverage/clover.xml # Or your specific coverage file

      - name: Run functional tests
        run: bats tests/bats/functional.bats
        env:
          N98_MAGERUN_BIN: ./bin/n98-magerun2
